### ISSUE TITLE
Inquiry about the Front-End Software Developer position

### ISSUE THREAD

**Issue by zhiyelee** [rackspace/rackspace_jobs#13]
May I know the  location for this position? [Front-End Software Developer](https://github.com/rackspace/rackspace_jobs/blob/master/devops_automation/Front_End_Software_Developer.md)

**Comment by jmontemayor** [comment]
We are a remote team and have folks in San Antonio, Austin, Dallas, Seattle, Sweden and Zurich.  Our headquarters is out of San Antonio TX.

**Comment by zhiyelee** [comment]
Great! thank you! @jmontemayor @rgbkrk

**Comment by zhiyelee** [comment]
@jmontemayor I have sent a mail days ago to the email in the page, but no response.
